// Sample restaurant data + copy translations

const RESTAURANTS = [
  {
    id: 'al-nour',
    name: 'Al-Nour Restaurant',
    district: 10,
    districtName: 'Favoriten',
    status: 'verified',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Familiär', 'Lieferung', 'Vegetarisch'],
    price: '€€',
    rating: 4.7,
    reviews: 284,
    // map coordinates (projected onto our fake map svg viewBox 0..100)
    x: 52, y: 78,
    // Warm image gradients (food vibe) — placeholders until real photos
    img: ['#7C2D12', '#431407'],
    accentHue: 18,
    featured: true,
  },
  {
    id: 'pizza-medina',
    name: 'Pizza Medina',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Pizza'],
    tags: ['Take-away', 'Familiär'],
    price: '€',
    rating: 4.2,
    reviews: 126,
    x: 34, y: 70,
    img: ['#713F12', '#422006'],
    accentHue: 38,
  },
  {
    id: 'cafe-istanbul',
    name: 'Café Istanbul',
    district: 20,
    districtName: 'Brigittenau',
    status: 'verified',
    categories: ['Cafe'],
    tags: ['Frühstück', 'Terrasse'],
    price: '€€',
    rating: 4.8,
    reviews: 412,
    x: 48, y: 24,
    img: ['#064E3B', '#022c22'],
    accentHue: 160,
  },
  {
    id: 'bosphorus-grill',
    name: 'Bosphorus Grill',
    district: 3,
    districtName: 'Landstraße',
    status: 'unknown',
    categories: ['Restaurant'],
    tags: ['Dinner', 'Gruppe'],
    price: '€€€',
    rating: 4.1,
    reviews: 58,
    x: 62, y: 52,
    img: ['#1F2937', '#0b1220'],
    accentHue: 210,
  },
  {
    id: 'halal-brothers',
    name: 'Halal Brothers',
    district: 1,
    districtName: 'Innere Stadt',
    status: 'self',
    categories: ['Kebab'],
    tags: ['Schnell', 'Late-night'],
    price: '€',
    rating: 4.4,
    reviews: 937,
    x: 52, y: 50,
    img: ['#78350F', '#451a03'],
    accentHue: 28,
  },
  {
    id: 'sultan-baklava',
    name: 'Sultan Baklava',
    district: 15,
    districtName: 'Rudolfsheim',
    status: 'verified',
    categories: ['Cafe'],
    tags: ['Dessert', 'Take-away'],
    price: '€',
    rating: 4.9,
    reviews: 203,
    x: 32, y: 52,
    img: ['#7F1D1D', '#450a0a'],
    accentHue: 350,
  },
  {
    id: 'damaskus-haus',
    name: 'Damaskus Haus',
    district: 16,
    districtName: 'Ottakring',
    status: 'verified',
    categories: ['Restaurant'],
    tags: ['Syrisch', 'Familie'],
    price: '€€',
    rating: 4.6,
    reviews: 178,
    x: 24, y: 44,
    img: ['#1E3A1E', '#052e16'],
    accentHue: 130,
  },
  {
    id: 'falafel-freddy',
    name: 'Falafel Freddy',
    district: 7,
    districtName: 'Neubau',
    status: 'verified',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Vegan', 'Schnell'],
    price: '€',
    rating: 4.5,
    reviews: 621,
    x: 44, y: 44,
    img: ['#3F3F46', '#18181B'],
    accentHue: 60,
  },
  {
    id: 'pizzeria-amici',
    name: 'Pizzeria Amici',
    district: 6,
    districtName: 'Mariahilf',
    status: 'self',
    categories: ['Pizza'],
    tags: ['Ofen', 'Romantisch'],
    price: '€€',
    rating: 4.3,
    reviews: 302,
    x: 42, y: 56,
    img: ['#7C2D12', '#431407'],
    accentHue: 12,
  },
];

const COPY = {
  de: {
    // Header
    navHome: 'Home',
    navSubmit: 'Eintragen',
    navImprint: 'Impressum',
    // Hero
    heroTagline: 'Halal-freundliche Restaurants in Wien entdecken',
    searchPlaceholder: 'Restaurant, Küche oder Bezirk suchen…',
    // Filter
    verifiedOnly: 'Nur verifiziert',
    district: 'Bezirk',
    allDistricts: 'Alle Bezirke',
    // Status
    statusVerified: 'Verifiziert',
    statusSelf: 'Selbstauskunft',
    statusUnknown: 'Unbekannt',
    // Results
    resultsCount: (n) => `${n} ${n === 1 ? 'Restaurant' : 'Restaurants'} in Wien`,
    emptyTitle: 'Keine Ergebnisse',
    emptyBody: 'Versuche einen anderen Bezirk oder eine andere Kategorie.',
    reset: 'Filter zurücksetzen',
    featured: 'Empfohlen',
    reviewsSuffix: (n) => `${n} Bewertungen`,
    // Map
    mapHeading: 'Karte',
    mapSub: 'Alle Lokale auf einen Blick — gefiltert nach deinen Kriterien.',
    districtLabel: (n, name) => `${1000 + n * 10} ${name}`,
    // Footer
    footerBlurb: 'Der ehrliche halal-freundliche Guide für Wien. Verifiziert, transparent, werbefrei.',
    footerSections: {
      product: ['Home', 'Eintragen', 'Karte', 'Bezirke'],
      company: ['Über uns', 'Impressum', 'Datenschutz', 'Kontakt'],
    },
    footerSectionTitles: { product: 'Produkt', company: 'Rechtliches' },
    footerLinks: {
      'Home': 'Akiwi Homepage.html',
      'Eintragen': 'Akiwi For Owners.html',
      'Karte': 'Akiwi Search.html',
      'Bezirke': 'Akiwi Search.html',
      'Über uns': 'Akiwi About.html',
      'Impressum': 'Akiwi Impressum.html',
      'Datenschutz': 'Akiwi Datenschutz.html',
      'Kontakt': 'Akiwi About.html',
    },
    footerMadeWith: 'Gemacht mit ❤️ für Wien',
    newsletter: 'Neue Lokale per E-Mail',
    newsletterCta: 'Anmelden',
    copyright: '© 2026 Akiwi.at — Alle Rechte vorbehalten.',
  },
  en: {
    navHome: 'Home',
    navSubmit: 'Submit',
    navImprint: 'Imprint',
    heroTagline: 'Discover halal-friendly restaurants across Vienna',
    searchPlaceholder: 'Search restaurants, cuisines, or districts…',
    verifiedOnly: 'Verified only',
    district: 'District',
    allDistricts: 'All districts',
    statusVerified: 'Verified',
    statusSelf: 'Self-declared',
    statusUnknown: 'Unknown',
    resultsCount: (n) => `${n} ${n === 1 ? 'restaurant' : 'restaurants'} in Vienna`,
    emptyTitle: 'No results',
    emptyBody: 'Try a different district or category.',
    reset: 'Reset filters',
    featured: 'Featured',
    reviewsSuffix: (n) => `${n} reviews`,
    mapHeading: 'Map',
    mapSub: 'Every venue at a glance — filtered to match your picks.',
    districtLabel: (n, name) => `${1000 + n * 10} ${name}`,
    footerBlurb: 'The honest halal-friendly guide to Vienna. Verified, transparent, ad-free.',
    footerSections: {
      product: ['Home', 'Submit', 'Map', 'Districts'],
      company: ['About', 'Imprint', 'Privacy', 'Contact'],
    },
    footerSectionTitles: { product: 'Product', company: 'Legal' },
    footerLinks: {
      'Home': 'Akiwi Homepage.html',
      'Submit': 'Akiwi For Owners.html',
      'Map': 'Akiwi Search.html',
      'Districts': 'Akiwi Search.html',
      'About': 'Akiwi About.html',
      'Imprint': 'Akiwi Impressum.html',
      'Privacy': 'Akiwi Datenschutz.html',
      'Contact': 'Akiwi About.html',
    },
    footerMadeWith: 'Made with ❤️ for Vienna',
    newsletter: 'New venues by email',
    newsletterCta: 'Subscribe',
    copyright: '© 2026 Akiwi.at — All rights reserved.',
  },
};

const CATEGORIES = ['Restaurant', 'Kebab', 'Pizza', 'Cafe'];
const DISTRICTS = Array.from({ length: 23 }, (_, i) => i + 1);

Object.assign(window, { RESTAURANTS, COPY, CATEGORIES, DISTRICTS });
