// Sample restaurant data + copy translations

const RESTAURANTS = [
  {
    id: 'alaturka-1030',
    name: 'Alaturka Erdbergstraße',
    district: 3,
    districtName: 'Landstraße',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Take-away', 'Schnell', 'Türkisch'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 60, y: 52,
    img: ['#7C2D12', '#431407'],
    accentHue: 18,
  },
  {
    id: 'alaturka-1120',
    name: 'Alaturka Am Schöpfwerk',
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Take-away', 'Schnell', 'Türkisch'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 38, y: 70,
    img: ['#92400E', '#451A03'],
    accentHue: 28,
  },
  {
    id: 'alaturka-1150',
    name: 'Alaturka MaHü',
    district: 15,
    districtName: 'Rudolfsheim-Fünfhaus',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Take-away', 'Schnell', 'Türkisch'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 32, y: 52,
    img: ['#7F1D1D', '#450A0A'],
    accentHue: 8,
  },
  {
    id: 'alaturka-1230',
    name: 'Alaturka Alterlaa',
    district: 23,
    districtName: 'Liesing',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Take-away', 'Schnell', 'Türkisch'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 38, y: 88,
    img: ['#713F12', '#422006'],
    accentHue: 38,
  },
  {
    id: 'alaturka-2700',
    name: 'Alaturka Wiener Neustadt',
    district: 0,
    districtName: 'Wiener Neustadt',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Take-away', 'Schnell', 'Türkisch', 'Niederösterreich'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 78, y: 95,
    img: ['#78350F', '#451a03'],
    accentHue: 22,
  },
  {
    id: 'antep-evi',
    name: 'Antep Evi Grillhaus',
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Türkisch', 'Gaziantep', 'Pide', 'Lahmacun'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 36, y: 66,
    img: ['#1E3A1E', '#052e16'],
    accentHue: 130,
  },
  {
    id: 'damla',
    name: 'Damla Cafe-Konditorei-Bäckerei',
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Restaurant', 'Cafe', 'Pizza'],
    tags: ['Türkisch', 'Konditorei', 'Bäckerei', 'Lieferung', 'Baklava'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 36, y: 68,
    img: ['#7F1D1D', '#450A0A'],
    accentHue: 350,
  },
  {
    id: 'bakis-schnitzelparadies',
    name: "Baki's Schnitzelparadies",
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Restaurant'],
    tags: ['Schnitzel', 'Grill', 'Österreichisch', 'Lieferung', 'Take-away'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 38, y: 65,
    img: ['#78350F', '#451a03'],
    accentHue: 38,
  },
  {
    id: 'le-doener',
    name: 'Le Döner',
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Kebab', 'Pizza'],
    tags: ['Bio', 'Türkisch', 'Hawaiian', 'Lieferung', 'Take-away', 'Ohne Zusatzstoffe'],
    price: '€',
    rating: 4.0,
    reviews: 0,
    x: 39, y: 65,
    img: ['#1E3A8A', '#0c1e42'],
    accentHue: 200,
  },
  {
    id: 'burgallio-1120',
    name: 'Burgallio Meidling',
    district: 12,
    districtName: 'Meidling',
    status: 'unknown',
    categories: ['Restaurant'],
    tags: ['Burger', 'Vegan', 'Snacks', 'Lieferung', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 39, y: 66,
    img: ['#7C2D12', '#431407'],
    accentHue: 12,
  },
  {
    id: 'burgallio-1100',
    name: 'Burgallio Favoriten',
    district: 10,
    districtName: 'Favoriten',
    status: 'unknown',
    categories: ['Restaurant'],
    tags: ['Burger', 'Vegan', 'Snacks', 'Lieferung', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 52, y: 75,
    img: ['#92400E', '#451A03'],
    accentHue: 18,
  },
  {
    id: 'burgallio-1170',
    name: 'Burgallio Hernals',
    district: 17,
    districtName: 'Hernals',
    status: 'unknown',
    categories: ['Restaurant'],
    tags: ['Burger', 'Vegan', 'Snacks', 'Lieferung', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 28, y: 38,
    img: ['#7F1D1D', '#450A0A'],
    accentHue: 0,
  },
  {
    id: 'liwan-1120',
    name: 'Liwan Restaurant Meidling',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Libanesisch'],
    tags: ['Syrisch', 'Arabisch', 'Grill', 'Halal', 'Vegan', 'Lieferung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 40, y: 68,
    img: ['#1E5C4A', '#0B3D2C'],
    accentHue: 160,
  },
  {
    id: 'liwan-1200',
    name: 'Liwan Restaurant Brigittenau',
    district: 20,
    districtName: 'Brigittenau',
    status: 'self',
    categories: ['Restaurant', 'Libanesisch'],
    tags: ['Syrisch', 'Arabisch', 'Grill', 'Halal', 'Vegan', 'Lieferung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 52, y: 42,
    img: ['#1E5C4A', '#0B3D2C'],
    accentHue: 160,
  },
  {
    id: 'ava-persisch-1120',
    name: 'AVA Persisches Restaurant',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Persisch'],
    tags: ['Iranisch', 'Grill', 'Safran-Reis', 'Gehobenes Ambiente', 'Reservierung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 40, y: 67,
    img: ['#5C1A1A', '#2D0A0A'],
    accentHue: 350,
  },
  {
    id: 'motelli-1120',
    name: 'Motelli Restaurant',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Italienisch'],
    tags: ['Mediterran', 'Pizza', 'Pasta', 'Schanigarten', 'WLAN', 'Mittagstisch'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 40, y: 67,
    img: ['#C85A17', '#6B3410'],
    accentHue: 25,
  },
  {
    id: 'cardak-1120',
    name: 'Restaurant Čardak',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Balkanisch'],
    tags: ['Makedonisch', 'Balkan', 'Grill', 'Halal', 'Tontopfgerichte', 'Lieferung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 41, y: 67,
    img: ['#8B3A1D', '#C85A17'],
    accentHue: 28,
  },
  {
    id: 'turkis-city',
    name: 'Türkis City',
    district: 1,
    districtName: 'Innere Stadt',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 55, y: 50,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-landstrasse',
    name: 'Türkis Landstraße',
    district: 3,
    districtName: 'Landstraße',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 60, y: 55,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-neubau',
    name: 'Türkis Neubau',
    district: 7,
    districtName: 'Neubau',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 45, y: 45,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-meidling',
    name: 'Türkis Meidling',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 40, y: 72,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-westbahnhof',
    name: 'Türkis Westbahnhof',
    district: 15,
    districtName: 'Rudolfsheim-Fünfhaus',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 35, y: 45,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-millennium',
    name: 'Türkis Millennium City',
    district: 20,
    districtName: 'Brigittenau',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 65, y: 30,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'turkis-donau',
    name: 'Türkis Donau Zentrum',
    district: 22,
    districtName: 'Donaustadt',
    status: 'self',
    categories: ['Restaurant', 'Kebab'],
    tags: ['Orientalisch', 'Grill', 'Halal', 'Lieferung', 'Catering', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 70, y: 25,
    img: ['#0D9488', '#14B8A6'],
    accentHue: 190,
  },
  {
    id: 'kent-1100',
    name: 'Kent Favoriten',
    district: 10,
    districtName: 'Favoriten',
    status: 'self',
    categories: ['Restaurant', 'Türkisch'],
    tags: ['Türkisch', 'Levantinisch', 'Grill', 'Halal', 'Bäckerei', 'Frühstück', 'Lieferung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 50, y: 75,
    img: ['#A0522D', '#CD853F'],
    accentHue: 15,
  },
  {
    id: 'kent-1150',
    name: 'Kent Rudolfsheim',
    district: 15,
    districtName: 'Rudolfsheim-Fünfhaus',
    status: 'self',
    categories: ['Restaurant', 'Türkisch'],
    tags: ['Türkisch', 'Levantinisch', 'Grill', 'Halal', 'Bäckerei', 'Frühstück', 'Stammhaus'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 35, y: 50,
    img: ['#A0522D', '#CD853F'],
    accentHue: 15,
  },
  {
    id: 'kent-1160',
    name: 'Kent Ottakring',
    district: 16,
    districtName: 'Ottakring',
    status: 'self',
    categories: ['Restaurant', 'Türkisch'],
    tags: ['Türkisch', 'Levantinisch', 'Grill', 'Halal', 'Bäckerei', 'Frühstück', 'Brunnenmarkt'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 30, y: 40,
    img: ['#A0522D', '#CD853F'],
    accentHue: 15,
  },
  {
    id: 'kent-1200',
    name: 'Kent Brigittenau',
    district: 20,
    districtName: 'Brigittenau',
    status: 'self',
    categories: ['Restaurant', 'Türkisch'],
    tags: ['Türkisch', 'Levantinisch', 'Grill', 'Halal', 'Bäckerei', 'Frühstück', 'Lieferung'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 65, y: 35,
    img: ['#A0522D', '#CD853F'],
    accentHue: 15,
  },
  {
    id: 'akakiko-city',
    name: 'Akakiko City',
    district: 1,
    districtName: 'Innere Stadt',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 55, y: 50,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  {
    id: 'akakiko-gerngross',
    name: 'Akakiko Gerngross',
    district: 7,
    districtName: 'Neubau',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 45, y: 45,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  {
    id: 'akakiko-meidling',
    name: 'Akakiko Meidling',
    district: 12,
    districtName: 'Meidling',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 40, y: 70,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  {
    id: 'akakiko-westbahnhof',
    name: 'Akakiko Westbahnhof',
    district: 15,
    districtName: 'Rudolfsheim-Fünfhaus',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 35, y: 45,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  {
    id: 'akakiko-millennium',
    name: 'Akakiko Millennium City',
    district: 20,
    districtName: 'Brigittenau',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 65, y: 30,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  {
    id: 'akakiko-donau',
    name: 'Akakiko Donau Zentrum',
    district: 22,
    districtName: 'Donaustadt',
    status: 'self',
    categories: ['Restaurant', 'Asiatisch'],
    tags: ['Japanisch', 'Koreanisch', 'Thailändisch', 'Sushi', 'Halal', 'Lieferung', 'Schnell', 'Take-away'],
    price: '€€',
    rating: 4.0,
    reviews: 0,
    x: 70, y: 25,
    img: ['#B91C1C', '#DC2626'],
    accentHue: 0,
  },
  // ── Pizza Mann (Österreichweite Kette) ──
  {
    id: 'pizza-mann-wien-02',
    name: 'Pizza Mann Ausstellungsstraße',
    district: 2,
    districtName: 'Leopoldstadt',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 4.1,
    reviews: 48,
    x: 38, y: 52,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-wien-10',
    name: 'Pizza Mann Quellenstraße',
    district: 10,
    districtName: 'Favoriten',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 4.0,
    reviews: 52,
    x: 42, y: 28,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-wien-14',
    name: 'Pizza Mann Linzer Straße',
    district: 14,
    districtName: 'Penzing',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 3.9,
    reviews: 45,
    x: 28, y: 28,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-wien-21',
    name: 'Pizza Mann Prager Straße',
    district: 21,
    districtName: 'Floridsdorf',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Restaurant'],
    price: '€€',
    rating: 4.2,
    reviews: 61,
    x: 42, y: 58,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-wien-22',
    name: 'Pizza Mann Wagramer Straße',
    district: 22,
    districtName: 'Donaustadt',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 4.0,
    reviews: 55,
    x: 50, y: 52,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-graz',
    name: 'Pizza Mann Graz',
    district: 0,
    districtName: 'Graz',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Restaurant'],
    price: '€€',
    rating: 4.1,
    reviews: 58,
    x: 15, y: 20,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-linz-zentrum',
    name: 'Pizza Mann Linz Zentrum',
    district: 0,
    districtName: 'Linz',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 4.0,
    reviews: 50,
    x: 28, y: 65,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-linz-restaurant',
    name: 'Pizza Mann Linz Restaurant',
    district: 0,
    districtName: 'Linz',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Restaurant'],
    price: '€€',
    rating: 4.2,
    reviews: 63,
    x: 30, y: 68,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-leonding',
    name: 'Pizza Mann Leonding',
    district: 0,
    districtName: 'Leonding',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Restaurant'],
    price: '€€',
    rating: 4.0,
    reviews: 47,
    x: 26, y: 62,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-salzburg',
    name: 'Pizza Mann Salzburg',
    district: 0,
    districtName: 'Salzburg',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 4.1,
    reviews: 54,
    x: 8, y: 80,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-innsbruck',
    name: 'Pizza Mann Innsbruck',
    district: 0,
    districtName: 'Innsbruck',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Store'],
    price: '€€',
    rating: 3.9,
    reviews: 49,
    x: 2, y: 72,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
  {
    id: 'pizza-mann-wels',
    name: 'Pizza Mann Wels',
    district: 0,
    districtName: 'Wels',
    status: 'verified',
    categories: ['Restaurant', 'Pizza'],
    tags: ['Pizza', 'Lieferung', 'Halal', 'Schnell', 'Restaurant'],
    price: '€€',
    rating: 4.1,
    reviews: 56,
    x: 24, y: 75,
    img: ['#B45309', '#FBBF24'],
    accentHue: 15,
  },
];

const COPY = {
  de: {
    // Header
    navHome: 'Home',
    navSubmit: 'Eintragen',
    navImprint: 'Impressum',
    // Hero
    heroTagline: 'Halal-freundliche Restaurants in Österreich entdecken',
    searchPlaceholder: 'Restaurant, Küche oder Bezirk suchen…',
    // Filter
    verifiedOnly: 'Nur verifiziert',
    district: 'Bezirk',
    allDistricts: 'Alle Bezirke',
    // Status
    statusVerified: 'Verifiziert',
    statusSelf: 'Selbstauskunft',
    statusUnknown: 'Unbekannt',
    // Results
    resultsCount: (n) => `${n} ${n === 1 ? 'Restaurant' : 'Restaurants'} in Österreich`,
    emptyTitle: 'Keine Ergebnisse',
    emptyBody: 'Versuche einen anderen Bezirk oder eine andere Kategorie.',
    reset: 'Filter zurücksetzen',
    featured: 'Empfohlen',
    reviewsSuffix: (n) => `${n} Bewertungen`,
    // Map
    mapHeading: 'Karte',
    mapSub: 'Alle Lokale auf einen Blick — gefiltert nach deinen Kriterien.',
    districtLabel: (n, name) => `${1000 + n * 10} ${name}`,
    // Footer
    footerBlurb: 'Der ehrliche halal-freundliche Guide für Österreich. Verifiziert, transparent, werbefrei.',
    footerSections: {
      product: ['Home', 'Eintragen', 'Karte', 'Bezirke'],
      company: ['Über uns', 'Impressum', 'Datenschutz', 'Kontakt'],
    },
    footerSectionTitles: { product: 'Produkt', company: 'Rechtliches' },
    footerLinks: {
      'Home': 'Akiwi Homepage.html',
      'Eintragen': 'Akiwi For Owners.html',
      'Karte': 'Akiwi Search.html',
      'Bezirke': 'Akiwi Search.html',
      'Über uns': 'Akiwi About.html',
      'Impressum': 'Akiwi Impressum.html',
      'Datenschutz': 'Akiwi Datenschutz.html',
      'Kontakt': 'Akiwi About.html',
    },
    footerMadeWith: 'Gemacht mit ❤️ für Österreich',
    newsletter: 'Neue Lokale per E-Mail',
    newsletterCta: 'Anmelden',
    copyright: '© 2026 Akiwi.at — Alle Rechte vorbehalten.',
  },
  en: {
    navHome: 'Home',
    navSubmit: 'Submit',
    navImprint: 'Imprint',
    heroTagline: 'Discover halal-friendly restaurants across Austria',
    searchPlaceholder: 'Search restaurants, cuisines, or districts…',
    verifiedOnly: 'Verified only',
    district: 'District',
    allDistricts: 'All districts',
    statusVerified: 'Verified',
    statusSelf: 'Self-declared',
    statusUnknown: 'Unknown',
    resultsCount: (n) => `${n} ${n === 1 ? 'restaurant' : 'restaurants'} in Austria`,
    emptyTitle: 'No results',
    emptyBody: 'Try a different district or category.',
    reset: 'Reset filters',
    featured: 'Featured',
    reviewsSuffix: (n) => `${n} reviews`,
    mapHeading: 'Map',
    mapSub: 'Every venue at a glance — filtered to match your picks.',
    districtLabel: (n, name) => `${1000 + n * 10} ${name}`,
    footerBlurb: 'The honest halal-friendly guide to Austria. Verified, transparent, ad-free.',
    footerSections: {
      product: ['Home', 'Submit', 'Map', 'Districts'],
      company: ['About', 'Imprint', 'Privacy', 'Contact'],
    },
    footerSectionTitles: { product: 'Product', company: 'Legal' },
    footerLinks: {
      'Home': 'Akiwi Homepage.html',
      'Submit': 'Akiwi For Owners.html',
      'Map': 'Akiwi Search.html',
      'Districts': 'Akiwi Search.html',
      'About': 'Akiwi About.html',
      'Imprint': 'Akiwi Impressum.html',
      'Privacy': 'Akiwi Datenschutz.html',
      'Contact': 'Akiwi About.html',
    },
    footerMadeWith: 'Made with ❤️ for Austria',
    newsletter: 'New venues by email',
    newsletterCta: 'Subscribe',
    copyright: '© 2026 Akiwi.at — All rights reserved.',
  },
};

const CATEGORIES = ['Restaurant', 'Kebab', 'Pizza', 'Cafe'];
const DISTRICTS = Array.from({ length: 23 }, (_, i) => i + 1);

Object.assign(window, { RESTAURANTS, COPY, CATEGORIES, DISTRICTS });
