// Verification page — copy & content
const VERIFICATION_COPY = {
  de: {
    nav: 'Verifizierung',
    eyebrow: 'Wie wir verifizieren',
    title: 'Vertrauen, das du sehen kannst.',
    subtitle: 'Akiwi prüft jedes halal-freundliche Lokal nach denselben Kriterien — und zeigt dir transparent, woher unser Urteil kommt. Keine Bezahl-Bewertungen. Keine Werbung.',
    ctaPrimary: 'Lokal eintragen',
    ctaSecondary: 'Problem melden',
    statsTitle: 'Akiwi in Zahlen',
    stats: [
      { v: '142', l: 'Verifizierte Lokale' },
      { v: '23', l: 'Wiener Bezirke' },
      { v: '1.840', l: 'Community-Hinweise' },
      { v: '0 €', l: 'Werbe-Einnahmen' },
    ],
    statusH: 'Drei Stufen. Klar getrennt.',
    statusSub: 'Wir lügen nicht über das, was wir nicht wissen.',
    statuses: [
      {
        key: 'verified',
        label: 'Verifiziert',
        title: 'Mit eigenen Augen geprüft.',
        body: 'Ein Mitglied des Akiwi-Teams war vor Ort, hat den halal-Lieferschein gesehen, die Speisekarte geprüft und den Betrieb dokumentiert. Wir verifizieren jedes Lokal alle 12 Monate erneut.',
        bullets: [
          'Halal-zertifizierter Fleisch-Lieferant',
          'Kein Alkohol auf der Karte',
          'Dokumente eingesehen (Zertifikat + Foto)',
          'Re-Check alle 12 Monate',
        ],
      },
      {
        key: 'self',
        label: 'Selbstauskunft',
        title: 'Vom Lokal angegeben — von uns noch nicht geprüft.',
        body: 'Das Lokal hat sich als halal-freundlich eingetragen. Wir glauben das, aber wir konnten es noch nicht selbst bestätigen. Behandle diesen Status als Hinweis, nicht als Garantie.',
        bullets: [
          'Eintrag durch das Lokal selbst',
          'Keine Vor-Ort-Prüfung erfolgt',
          'Frag nach, bevor du bestellst',
          'Du kannst beitragen — Foto vom Zertifikat senden',
        ],
      },
      {
        key: 'unknown',
        label: 'Unbekannt',
        title: 'Wir haben keine verlässliche Information.',
        body: 'Das Lokal taucht in Karten auf oder wurde von Nutzer:innen erwähnt — aber niemand konnte uns belegen, dass es halal serviert. Wir behaupten nichts. Wenn du Bescheid weißt — schreib uns.',
        bullets: [
          'Aus öffentlichen Quellen importiert',
          'Keine Halal-Bestätigung erhalten',
          'Status kann sich jederzeit ändern',
          'Hilfe willkommen',
        ],
      },
    ],
    criteriaH: 'Was wir prüfen — jedes Mal.',
    criteriaSub: 'Drei harte Kriterien für den grünen Status. Keine Ausnahmen, keine Sonderfälle.',
    criteria: [
      {
        n: '01',
        title: 'Zertifizierter Halal-Lieferant',
        body: 'Das Fleisch stammt nachweislich von einem in Österreich oder der EU zertifizierten Halal-Schlachthof. Wir verlangen Lieferschein oder Vertragsnachweis und vergleichen ihn mit der ausgewiesenen Liste anerkannter Stellen.',
        meta: 'Beleg: Lieferschein + Foto der Verpackung',
      },
      {
        n: '02',
        title: 'Kein Alkohol im Angebot',
        body: 'Auf der Speise- und Getränkekarte ist kein Alkohol gelistet — auch nicht in Saucen, Desserts oder Cocktails. Wenn ein Lokal Alkohol verkauft, kann es nicht den grünen Status erhalten, auch wenn das Fleisch halal ist.',
        meta: 'Beleg: Speisekarte komplett gesichtet',
      },
      {
        n: '03',
        title: 'Geprüfte Dokumente',
        body: 'Wir sehen das Originalzertifikat des Lieferanten, Fotos der Fleisch-Verpackung mit Halal-Stempel und — wenn möglich — die Lager-Trennung von Halal- und Nicht-Halal-Ware. Alles wird in unserer internen Datenbank gespeichert.',
        meta: 'Aufbewahrt: 24 Monate, datenschutzkonform',
      },
    ],
    processH: 'So läuft die Verifizierung ab.',
    processSub: 'Im Schnitt 14 Tage vom Eintrag bis zum grünen Badge.',
    processSteps: [
      { n: 1, t: 'Eintrag', body: 'Das Lokal — oder eine Nutzer:in — meldet das Restaurant über unser Formular.', when: 'Tag 0' },
      { n: 2, t: 'Erstkontakt', body: 'Wir kontaktieren das Lokal, erklären den Prozess und bitten um Dokumente.', when: 'Tag 1–3' },
      { n: 3, t: 'Vor-Ort-Besuch', body: 'Ein Akiwi-Team-Mitglied besucht das Lokal unangekündigt, prüft Karte, Lieferanten und Lager.', when: 'Tag 4–10' },
      { n: 4, t: 'Veröffentlichung', body: 'Bei bestandener Prüfung wird der grüne Badge vergeben. Re-Check in 12 Monaten.', when: 'Tag 14' },
    ],
    methodologyH: 'Unsere Methodik',
    methodologyBody: 'Wir sind keine staatliche Stelle und kein Zertifizierer. Akiwi ist ein unabhängiges, werbefreies Verzeichnis: Wir prüfen das, was prüfbar ist, und sind ehrlich über Grenzen. Konflikte mit Lokalen lösen wir öffentlich.',
    pillars: [
      { t: 'Unabhängig', d: 'Keine bezahlten Einträge, keine bezahlten Badges, kein Affiliate.' },
      { t: 'Transparent', d: 'Jedes Kriterium und jeder Schritt sind hier dokumentiert.' },
      { t: 'Korrigierbar', d: 'Falsche Einschätzungen werden korrigiert — sichtbar, mit Datum.' },
    ],
    ownerH: 'Du betreibst ein Lokal?',
    ownerSub: 'Trag dich kostenlos ein. Verifizierung ist und bleibt kostenlos.',
    ownerSteps: [
      'Eintrag-Formular ausfüllen',
      'Halal-Zertifikat hochladen',
      'Termin vor Ort vereinbaren',
      'Grünen Badge erhalten — bei Bedarf re-zertifizieren',
    ],
    ownerCta: 'Lokal kostenlos eintragen',
    faqH: 'Häufige Fragen',
    faq: [
      { q: 'Kostet die Verifizierung etwas?', a: 'Nein. Eintrag und Verifizierung sind und bleiben kostenlos. Akiwi finanziert sich über Spenden und Förderungen, nicht über Lokale.' },
      { q: 'Was, wenn ein Lokal zwischen zwei Re-Checks etwas ändert?', a: 'Schreib uns über „Problem melden“. Wir prüfen kurzfristig nach und passen den Status an, bevor das nächste Re-Check fällig ist.' },
      { q: 'Warum gibt es einen „gelben“ Status?', a: 'Weil wir nicht jedes Lokal sofort besuchen können. Gelb heißt: Das Lokal selbst sagt halal — aber wir konnten es noch nicht prüfen. Lieber ehrlich als falsch grün.' },
      { q: 'Akzeptiert ihr ein bestimmtes Halal-Zertifikat?', a: 'Wir akzeptieren Zertifikate von in Österreich und der EU anerkannten Halal-Stellen. Eine Liste pflegen wir laufend.' },
      { q: 'Kann ein Lokal den Status verlieren?', a: 'Ja. Wenn beim Re-Check Kriterien nicht mehr erfüllt sind oder begründete Hinweise eintreffen, ändern wir den Status öffentlich und mit Datum.' },
      { q: 'Wer steht hinter Akiwi?', a: 'Ein kleines Team aus Wien — Foodies, Entwickler:innen und Mitglieder der muslimischen Community. Mehr unter „Über uns“.' },
    ],
    bottomH: 'Hilf mit, Wien transparenter zu machen.',
    bottomBody: 'Egal ob du ein Lokal kennst, das fehlt, oder einen Fehler bei einer Bewertung gefunden hast — wir hören zu.',
    bottomCta1: 'Lokal eintragen',
    bottomCta2: 'Problem melden',
  },
  en: {
    nav: 'Verification',
    eyebrow: 'How verification works',
    title: 'Trust you can actually see.',
    subtitle: 'Akiwi checks every halal-friendly venue against the same criteria — and shows you exactly where our verdict comes from. No paid placements. No ads.',
    ctaPrimary: 'Submit a venue',
    ctaSecondary: 'Report a problem',
    statsTitle: 'Akiwi by the numbers',
    stats: [
      { v: '142', l: 'Verified venues' },
      { v: '23', l: 'Vienna districts' },
      { v: '1,840', l: 'Community signals' },
      { v: '€0', l: 'Ad revenue' },
    ],
    statusH: 'Three levels. Clearly separated.',
    statusSub: 'We don\u2019t lie about what we don\u2019t know.',
    statuses: [
      {
        key: 'verified',
        label: 'Verified',
        title: 'Checked with our own eyes.',
        body: 'A member of the Akiwi team visited the venue, saw the halal delivery slip, reviewed the menu and documented the operation. We re-check every 12 months.',
        bullets: [
          'Halal-certified meat supplier',
          'No alcohol on the menu',
          'Documents reviewed (certificate + photo)',
          'Re-check every 12 months',
        ],
      },
      {
        key: 'self',
        label: 'Self-declared',
        title: 'Stated by the venue — not yet verified by us.',
        body: 'The venue listed itself as halal-friendly. We trust them, but we haven\u2019t confirmed it ourselves yet. Treat this as a hint, not a guarantee.',
        bullets: [
          'Listed by the venue itself',
          'No on-site check yet',
          'Ask before you order',
          'You can help — send a photo of the certificate',
        ],
      },
      {
        key: 'unknown',
        label: 'Unknown',
        title: 'We have no reliable info.',
        body: 'The venue appears in maps or has been mentioned by users — but no one could prove to us it serves halal. We won\u2019t pretend. If you know — tell us.',
        bullets: [
          'Imported from public sources',
          'No halal confirmation received',
          'Status can change anytime',
          'Help welcome',
        ],
      },
    ],
    criteriaH: 'What we check — every time.',
    criteriaSub: 'Three hard criteria for the green status. No exceptions.',
    criteria: [
      {
        n: '01',
        title: 'Certified halal supplier',
        body: 'Meat verifiably comes from a halal slaughterhouse certified in Austria or the EU. We require a delivery slip or contract proof and cross-check it against our list of recognised bodies.',
        meta: 'Evidence: delivery slip + packaging photo',
      },
      {
        n: '02',
        title: 'No alcohol on offer',
        body: 'Neither the food nor drinks menu lists alcohol — including in sauces, desserts or cocktails. If a venue sells alcohol, it cannot get the green status, even if the meat is halal.',
        meta: 'Evidence: full menu reviewed',
      },
      {
        n: '03',
        title: 'Documents reviewed',
        body: 'We see the original supplier certificate, photos of meat packaging with halal stamp and — when possible — the storage separation between halal and non-halal goods. Everything is logged in our internal database.',
        meta: 'Stored: 24 months, GDPR-compliant',
      },
    ],
    processH: 'How verification runs.',
    processSub: 'On average 14 days from submission to green badge.',
    processSteps: [
      { n: 1, t: 'Submission', body: 'The venue — or a user — submits the restaurant via our form.', when: 'Day 0' },
      { n: 2, t: 'First contact', body: 'We reach out to the venue, explain the process and request documents.', when: 'Day 1–3' },
      { n: 3, t: 'On-site visit', body: 'An Akiwi team member visits the venue unannounced, checking menu, supplier and storage.', when: 'Day 4–10' },
      { n: 4, t: 'Publication', body: 'If the check passes, the green badge is granted. Re-check in 12 months.', when: 'Day 14' },
    ],
    methodologyH: 'Our methodology',
    methodologyBody: 'We are not a state body and not a certifier. Akiwi is an independent, ad-free directory: we verify what is verifiable and we\u2019re honest about limits. We resolve disputes with venues in public.',
    pillars: [
      { t: 'Independent', d: 'No paid listings, no paid badges, no affiliates.' },
      { t: 'Transparent', d: 'Every criterion and every step is documented here.' },
      { t: 'Correctable', d: 'Wrong calls get corrected — visibly, with a date.' },
    ],
    ownerH: 'Run a venue?',
    ownerSub: 'List for free. Verification is and stays free.',
    ownerSteps: [
      'Fill out the submission form',
      'Upload your halal certificate',
      'Schedule an on-site visit',
      'Receive the green badge — re-certify when due',
    ],
    ownerCta: 'List your venue for free',
    faqH: 'Frequently asked',
    faq: [
      { q: 'Does verification cost anything?', a: 'No. Listing and verification are and remain free. Akiwi is funded by donations and grants, not by venues.' },
      { q: 'What if a venue changes something between two re-checks?', a: 'Use "Report a problem". We\u2019ll re-check quickly and adjust the status before the next routine check.' },
      { q: 'Why is there a "yellow" status?', a: 'Because we can\u2019t visit every venue immediately. Yellow means: the venue says halal — we couldn\u2019t verify yet. Better honest than falsely green.' },
      { q: 'Do you accept any specific halal certificate?', a: 'We accept certificates from halal bodies recognised in Austria and the EU. We maintain a list and update it continuously.' },
      { q: 'Can a venue lose its status?', a: 'Yes. If criteria are no longer met at re-check, or credible reports come in, we change the status publicly and with a date.' },
      { q: 'Who is behind Akiwi?', a: 'A small Vienna team — foodies, developers and members of the Muslim community. More under "About".' },
    ],
    bottomH: 'Help us make Vienna more transparent.',
    bottomBody: 'Whether you know a venue we\u2019re missing or spotted a mistake in a rating — we\u2019re listening.',
    bottomCta1: 'Submit a venue',
    bottomCta2: 'Report a problem',
  },
};

window.VERIFICATION_COPY = VERIFICATION_COPY;
